pyapp-kit/superqt

- qwidgets/__init__.py
- qwidgets/spinbox/__init__.py
- qwidgets/spinbox/_intspin.py
- qwidgets/spinbox/_tests/test_large_int_spinbox.py
adds `QLargeIntSpinBox` from https://github.com/napari/napari/pull/2648
> add large int spinbox

- .gitignore
- superqt/sliders/_generic_slider.py
- superqt/sliders/_tests/test_generic_slider.py
fixes #8 and adds a test (there was a bug in `_sliderValueFromPosition`)  thanks @sofroniewn
> Fix range slider with negative min range

- docs/sliders.md
Hi Talley @tlambert03 ,
this just fixes a broken link in the docs.
Cheers,
Robert
> fix broken link

- .pre-commit-config.yaml
- examples/collapsible.py
- setup.cfg
- src/superqt/collapsible/_collapsible.py
- tests/test_collapsible.py
pre-commit CI wasn't turned on... This turns it on, fixes some linting issues, and (very slightly) modifies some of the QCollapsible methods and tests.
> Fix some small linting issues.

- setup.cfg
As we discussed in #45 , I am making a follow up PR here.
- initial commit
> typing-extensions version pinning

- src/superqt/sliders/_labeled.py
> Add missing signals on proxy sliders 

- src/superqt/sliders/_labeled.py
with @brisvag
Adds the option to toggle labels on QLabeledSlider using `sld.setEdgeLabelMode(mode)` where mode is one of `sld.EdgeLabelMode.NoLabel` or `sld.EdgeLabelMode.LabelIsValue`
closes #49
> add edgeLabelMode option to QLabeledSlider

- .github/workflows/test_and_deploy.yml
should fix windows failures on tests
> fix xvfb tests

- .github/workflows/test_and_deploy.yml
Adds a test to ensure compatibility with napari. (breakages are not strictly disallowed, but will likely indicate the need for a dependency bump at napari)
> add napari test to CI

- src/superqt/utils/__init__.py
- src/superqt/utils/_misc.py
- tests/test_utils.py
context manager that blocks signal emission from an object
```python
from superqt.utils import signals_blocked
with signals_blocked(obj):
obj.signal.emit()  # will be blocked
```
> Add `signals_blocked` util

- .github/workflows/test_and_deploy.yml
- setup.cfg
- src/superqt/utils/_throttler.py
see https://forum.image.sc/t/problem-with-qtpy-when-running-napari/63975/7
> put SignalInstance in TYPE_CHECKING clause, check min requirements

- .github/workflows/test_and_deploy.yml
- tests/test_sliders/_testutil.py
- tests/test_sliders/test_generic_slider.py
- tests/test_sliders/test_range_slider.py
- tests/test_sliders/test_single_value_sliders.py
fixes the deprecation warnings in Qt6 tests since 6.3 has been released
> fix deprecation warnings in tests

- src/superqt/collapsible/_collapsible.py
the fix for child widget resizing in #72 can, in some cases, cause a crazy collapse/expand animation loop.  This PR fixes that by turning off animations in the case where we're simply updating the height of the collapsible due to a child event
> Fix crazy animation loop on Qcollapsible

- docs/utils.md
- examples/code_highlight.py
- setup.cfg
- src/superqt/utils/__init__.py
- src/superqt/utils/_code_syntax_highlight.py
- tests/test_code_highlight.py
This PR adds code syntax highlight first introduced in https://github.com/napari/napari/pull/4414
> Add code syntax highlight utils

- setup.cfg
- src/superqt/utils/_qthreading.py
- src/superqt/utils/_throttler.py
> fix: relax runtime typing extensions requirement

- src/superqt/sliders/_generic_range_slider.py
> fix range slider drag crash on PyQt6

- src/superqt/sliders/_labeled.py
fixes #94
Sorry for the delay @looninho ... and thank you for the very clear and helpful example
> fix: fix missing labels after setValue

- .github/workflows/test_and_deploy.yml
- pyproject.toml
until we have time to solve the pyside6.5 issues, this pins the dep
> pin pyside6<6.5

- .github/workflows/test_and_deploy.yml
- tests/test_sliders/test_labeled_slider.py
after testing locally, I think this will fix one of the segfault-on-cleanup that we're seeing in windows pyside6
> add qtbot to test to fix windows segfault

- src/superqt/sliders/_labeled.py
- tests/test_sliders/test_labeled_slider.py
> fix: fix double slider label editing

- src/superqt/sliders/_labeled.py
> fix: focus events on QLabeledSlider

- docs/utilities/signal_utils.md
- src/superqt/utils/_misc.py
> docs: document signals blocked

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature.md
- docs/utilities/fonticon.md
- pyproject.toml
> docs: update fonticon docs

- examples/code_highlight.py
- pyproject.toml
I think packaging got added during #80  but removed during the PR.  this removes it from deps
> build: remove packaging dep

- src/superqt/iconify/__init__.py
- tests/test_iconify.py
name() returns the key used to create the icon
> feat: Add QIconifyIcon.name() method

- src/superqt/collapsible/_collapsible.py
> fix: better default size policy for qcollapsible

- src/superqt/collapsible/_collapsible.py
would make #231 easier if the main toggle button were publicly accessible
> feat: make toggle public

- src/superqt/sliders/_labeled.py
> fix: fix sliderReleased, sliderPressed signals, and setTracking

- .github/workflows/test_and_deploy.yml
- pyproject.toml
- src/superqt/sliders/_generic_slider.py
- src/superqt/sliders/_labeled.py
> fix: fix inverted appearance

- .github/workflows/test_and_deploy.yml
- CONTRIBUTING.md
- README.md
- docs/index.md
- examples/throttler_demo.py
- pyproject.toml
- src/superqt/cmap/_catalog_combo.py
- src/superqt/cmap/_cmap_combo.py
- src/superqt/combobox/_color_combobox.py
- src/superqt/combobox/_enum_combobox.py
- src/superqt/elidable/_eliding.py
- src/superqt/fonticon/_iconfont.py
- src/superqt/fonticon/_plugins.py
- src/superqt/fonticon/_qfont_icon.py
- src/superqt/selection/_searchable_tree_widget.py
- src/superqt/sliders/_generic_range_slider.py
- src/superqt/sliders/_labeled.py
- src/superqt/utils/_misc.py
- src/superqt/utils/_qthreading.py
- tests/test_searchable_tree.py
- tests/zz_test_sliders/test_labeled_slider.py
- tests/zz_test_sliders/test_range_slider.py
> build: drop py38

- src/superqt/iconify/__init__.py
slightly more informative error when failing to download an iconify icon
> fix: better warning for download error

- src/superqt/iconify/__init__.py
This PR just returns self from  `QIconifyIcon.addKey` ... to allow chaining
> feat: allow chaining of QIconifyIcon.addKey

- CONTRIBUTING.md
Small change.
Need to have `pre-commit` installed before `pre-commit install` works.
> Update CONTRIBUTING.md to install .[dev] first then pre-commit

- CONTRIBUTING.md
- pyproject.toml
Eep, sorry two other small details I didn't get to in the other PR because of your ninja speed!
> Update CONTRIBUTING.md to include [test] and mention Qt backend

- .github/workflows/test_and_deploy.yml
> test: drop old napari test
