pyapp-kit/superqt

- superqt/__init__.py
- superqt/utils/__init__.py
- superqt/utils/_message_handler.py
- superqt/utils/_tests/test_qmessage_handler.py
This adds a convenient way to intercept, store, and re-reroute Qt messages from stdout to a python logger:
```python
handler = QMessageHandler()
handler.install()  
with QMessageHandler() as handler:  
...
logger = logging.getLogger(__name__)
with QMessageHandler(logger):  
...
```
> Add QMessageHandler context manager

- docs/decorators.md
- superqt/__init__.py
- superqt/utils/__init__.py
- superqt/utils/_ensure_thread.py
- superqt/utils/_tests/test_ensure_thread.py
This PR adds two decorators:
* `ensure_main_tread` - force to function/method will be called in main thread.\
* `ensure_object_thread` - force to method of `QObject` instance to be executed in this object thread.
> Add `ensure_main_tread` and `ensure_object_thread`

- MANIFEST.in
- setup.cfg
- superqt/sliders/__init__.pyi
- superqt/utils/_ensure_thread.py
- superqt/utils/_ensure_thread.pyi
Since inline stubs for decorators with optional arguments that modify return params get a little ugly, i figure it makes more sense to put them in a stub file...  this adds stubs for `ensure_main_thread` and `ensure_object_thread`.  cc @Czaki
> Add type stubs for ensure_thread decorator

- superqt/utils/_ensure_thread.py
- superqt/utils/_tests/test_ensure_thread.py
This is `superqt` side of the fix bug mentioned in https://github.com/napari/napari/pull/3445. 
Without this fix following code will pass:
```python
class Test(Qobject):
@ensure_object_thread
def test_func(self, arg1):
pass
t = Test()
assert t.test_func.__name__ == "_func"
```
> Propagate function name in `ensure_main_thread` and `ensure_object_thread`

- src/superqt/sliders/_generic_range_slider.py
- src/superqt/sliders/_generic_slider.py
- src/superqt/sliders/_labeled.py
- tests/test_sliders/_testutil.py
- tests/test_sliders/test_generic_slider.py
- tests/test_sliders/test_range_slider.py
- tests/test_sliders/test_single_value_sliders.py
Trying this out on CI.  This gets around the problem described in #48 by overriding signal instance attributes at instantiation time.  It's really fugly, but it's the only way I can think of at the moment to deal with the changes in pyside6.2  without breaking superqt's API (without deprecation).  We can discuss whether we should generally change the signals API, but I think that should go elsewhere:
This uses the following pattern, which appears to work:
```py
class NewSlider(QSlider):
_fvalueChanged = Signal(float)
def __init__(self):
super().__init__()
self.valueChanged = self._fvalueChanged  # need to do the override after super().__init__
```
> Ugly but functional workaround for pyside6.2.1 breakages

- src/superqt/utils/_qthreading.py
- tests/test_threadworker.py
fixes napari/superqt#64
Threadworkers started within another thread weren't getting started because of the QTimer.singleshot call in the QRunnable.start method.  (because threads don't have event loops, and QTimer needs one).  This checks to see if we're running in a thread that has an event loop before queuing with QTimer, otherwise it starts the runnable immediately)
> Fix nested threadworker not starting

- examples/throttle_mouse_event.py
- examples/throttler_demo.py
- src/superqt/utils/__init__.py
- src/superqt/utils/_throttler.py
- tests/test_throttler.py
@brisvag is working on a pure python throttle/debouncer that would use python threading Timers.  i transpiled a Qt/C++ version from the KDToolbox and added a couple of convenience decorators that will work on the Qt side.  Will be interesting to see how performance compares between a Qt and python-threaded version (in a Qt Event loop at least), but it will probably be nice to have both/either.
There are two examples included here, but the gist of it is:
```python
from superqt.utils import qthrottled
my_signal.connect(qthrottled(my_callback, timeout=50))
```
or, as a decorator:
```python
class SomeWidget:
def __init__(self):
some_signal.connect(self._callback)
@qthrottled
def _callback(self):
...
```
cc @nclack, @sofroniewn,
https://user-images.githubusercontent.com/1609449/152525485-d3b36b …
> Qthrottler and debouncer

- src/superqt/collapsible/_collapsible.py
otherwise ... if a collapsible is expanded and the child widget changes size, it gets clipped.
> Fix height of expanded QCollapsible when child changes size

- src/superqt/collapsible/_collapsible.py
The button used for the Collapsible previously showed a black on
archlinux.
This fixes it to display properly.
Collapsilbe before fix:
Collapsilbe after fix:
Closes https://github.com/napari/superqt/issues/78
> Fix CSS for Collapsible

- src/superqt/sliders/_labeled.py
minor change on the order of operations when updating a labeled slider
> reorder label update signal

- src/superqt/fonticon/_qfont_icon.py
Catches and ignores a (buggy) deprecation warning about QPixmapCache.find.  
This was seemingly temporarily deprecated: https://doc.qt.io/qt-5/qpixmapcache-obsolete.html ... but it's back and undeprecated in Qt6.
see also https://stackoverflow.com/questions/57484593/how-to-fix-pyside2-qpixmapcache-find-deprecationwarning
> fix: catch qpixmap deprecation

- src/superqt/sliders/_labeled.py
- tests/test_sliders/test_labeled_slider.py
In the pyqt5 configuration, the `QLabeledSlider` throws an error due to `QDoubleSpinBox` returning a float rather than an int.
Here I propose to add a proxy `_setValue` function which does the conversion :)
> Fix float value error in pyqt configuration

- src/superqt/combobox/_enum_combobox.py
I found that recent version of pyside6 overwrite __str__ method of `Enum` class, so checking if str method belongs either to `enum` or `shibokensupport` modules solves this problem. 
But I'm not sure if it is a goo d idea as it may impact on some related enums. 
Maybe the best option will be to wait on the next PySide6 release? Maybe they will solve it?
fixes: #118
> Simple workaround for pyside 6

- src/superqt/sliders/_generic_slider.py
- src/superqt/sliders/_sliders.py
- tests/test_sliders/_testutil.py
- tests/test_sliders/test_float.py
- tests/test_sliders/test_generic_slider.py
- tests/test_sliders/test_labeled_slider.py
- tests/test_sliders/test_range_slider.py
fixes #115
closes #111
thank you @david-jenkins for the fix offered in #111 ... I wanted tests to make sure that we were both avoiding the TypeError while also emitting the proper types from the signals... and that led me down a deeper rabbit hole.
I think the ultimate fix was to change the root `_GenericSlider` as was done here... many tests added
> fix: Fix TypeError on slider rangeChanged signal

- .github/workflows/test_and_deploy.yml
- setup.cfg
- src/superqt/spinbox/_quantity.py
- tests/test_quantity.py
fixes a bug in `QQuantity` when using `setValue()` with an instance of `pint.Quantity`.  Also makes the initial value optional (defaulting to a dimensionless magnitude of zero)
> fix: fix quantity set value and add test

- setup.cfg
- src/superqt/fonticon/_qfont_icon.py
- src/superqt/utils/_code_syntax_highlight.py
- tests/test_sliders/_testutil.py
unpins pyside6 (now that qtpy is updated) and  fixes some deprecations
> build: unpin pyside6

- src/superqt/collapsible/_collapsible.py
- tests/test_collapsible.py
This PR adds a signal that is emitted when the toggle button to expand/collapse the widget is pressed.  This signal was needed in https://github.com/napari/napari/pull/5198 in order to resize another widget when the collapsible widget expands/collapses.
> Add signal to QCollapsible

- src/superqt/collapsible/_collapsible.py
This PR will only emit the toggle signal when the animate flag is True.  I realized that the signal was being emitted 3 times when it was not inside the `animate` if statement.  I don't know if its needed when `animate = False`, but for my purposes, I would prefer if this signal is not emitted several times per mouse click.
> Move QCollapsible toggle signal emit

- examples/qcollapsible.py
- src/superqt/collapsible/_collapsible.py
- tests/test_collapsible.py
- tests/test_fonticon/test_collapsible.py
This PR adds the ability to change the icon on the toggle QPushButton.  Currently, the icon is a part of the text string.  This PR will change it so that an icon is set on the button.  The original icon is still used if there isn't one set, however, the default string is used to create an icon.  
You can now instantiate a collapsible widget while also declaring an `expandedIcon` and/or `collapsedIcon`.  These icons can be a QIcon or a text string.
```
icon1 = icon(FA5S.smile, color='white')
icon2 = icon(FA5S.frown, color='white')
collapsible = QCollapsible("Advanced analysis", expandedIcon=icon1, collapsedIcon=icon2)
```
```
collapsible = QCollapsible("Advanced analysis", expandedIcon='-', collapsedIcon="+")
```
> feat: Change icon used in Collapsible widget

- examples/searchable_tree_widget.py
- src/superqt/__init__.py
- src/superqt/selection/__init__.py
- src/superqt/selection/_searchable_tree_widget.py
- tests/test_searchable_tree.py
This adds a searchable tree widget that can be initialized from a mapping. Mappings and iterables (other than strings) are traversed and populated in the tree. The tree has two columns.
The first column is either the key of a mapping or the enumerated index of an iterable, which can be searched based on regular expression. An item is shown if it, any of its ancestors, or any of its descendants match the expression. Ancestors are needed because tree items are only shown if all their ancestors are. Descendants are needed because if the user if look for a key that 
The second column is either the `str()` value (for terminal types) or the type itself (e.g. `dict`) for non-terminal iterables.
I think this closes #12 , though I have not tried to reimplement …
> Searchable tree widget from a mapping

- src/superqt/utils/_throttler.py
Lack of a set timer paren may delay timer deletion. It may create some of the observed problems with hanging timers. I'm not 100% sure, but adding this parent covers with general Qt memory model.
> Set parent of timer in throttler

- .github/workflows/test_and_deploy.yml
- pyproject.toml
looks like pyside 6.5.2 has fixed a lot of the issues with subclassing `Generic`.  haven't looked for/found the upstream Qt issue yet, but many things now work in local testing.  This PR unpins our pyside6 extra, and updates the test suite again
> build: unpin pyside6.5

- src/superqt/spinbox/_intspin.py
- tests/test_large_int_spinbox.py
needed for https://github.com/pyapp-kit/magicgui/pull/572
> feat: add stepType to largeInt spinbox

- src/superqt/utils/_throttler.py
- tests/test_throttler.py
Allow to use `qdebounced` and `qthrottled` on methods with proper setting parent if use Qt objects.
> Implement throttling of methods

- src/superqt/combobox/_enum_combobox.py
- tests/test_enum_comb_box.py
This PR removes duplicates/aliases from showing up in a QEnumCombo:
```
class MyEnum(Enum):
VALUE = 'value'
ALIAS = VALUE
```
should only show 'value' once, not twice
> fix: remove dupes/aliases in QEnumCombo

- docs/utilities/error_dialog_contexts.md
- mkdocs.yml
- src/superqt/utils/__init__.py
- src/superqt/utils/_errormsg_context.py
- tests/test_utils.py
```python
from qtpy.QtWidgets import QApplication
from superqt.utils import exceptions_as_dialog
app = QApplication([])
with exceptions_as_dialog():
raise Exception("This will be caught and shown in a QMessageBox")
with exceptions_as_dialog(msg_template="Error: {exc_value}"):
raise Exception("This message will be used as 'exc_value'")
for _i in range(3):
with exceptions_as_dialog(AssertionError, use_global_err_message=True):
raise AssertionError("Uncheck the checkbox to ignore this in the future")
app.exec()
```
> feat: add error `exceptions_as_dialog` context manager to catch and show Exceptions

- src/superqt/sliders/_labeled.py
this small change to the connections in QLabeledSlider seems to fix a mysterious segfault I occasionally get in another package.  Can't make reproducible test... but it's a tiny change that results in the same ultimate behavior
> fix: fix mysterious segfault

- examples/color_combo_box.py
- src/superqt/__init__.py
- src/superqt/combobox/__init__.py
- src/superqt/combobox/_color_combobox.py
- tests/test_color_combo.py
Qt has a QColorDialog, but it's too much if you just want to offer a fixed set of color options.  This adds a ComboBox variant to select from a list of colors.  It ended up taking a fair amount of qt-innards to make it attractive and useable.
cc @jni, I believe you wanted something like this at one point?
> feat: add QColorComboBox for picking single colors

- examples/labeled.py
- src/superqt/sliders/_labeled.py
This PR 
1. adds more type annotations to QSliders
2. fixes __init__ overloads for better IDE hinting
3. adds one more label mode `EdgeLabelMode.LabelIsValue | EdgeLabelMode.LabelIsRange` that will show the `value / maximum`
4. changes the default orientation from Qt.Vertical to Qt.Horizontal (almost every use case I could find on github was already using that in the `__init__` and it's the more common/useful default)
> refactor: Labeled slider updates

- src/superqt/collapsible/_collapsible.py
fixes #203 
not quite sure why that was like that ... might have been a combination of #140  not updating #37?  
but i think it's fine just to remove it
> fix: don't reuse text in qcollapsible

- examples/iconify.py
- pyproject.toml
- src/superqt/__init__.py
- src/superqt/fonticon/__init__.py
- src/superqt/iconify/__init__.py
- tests/test_iconify.py
[Iconify](https://icon-sets.iconify.design) is a pretty great API unifying pretty much all of the major font-icon libraries into a single API from which you can request standardized SVGs.  I wrapped the API in library [`pyconify`](https://github.com/pyapp-kit/pyconify) that makes it easier to work with in python, and caches all svgs locally for faster/offline usage (after first using online once).  This PR makes a simple QIcon wrapper:
```python
from qtpy.QtCore import QSize
from qtpy.QtWidgets import QApplication, QPushButton
from superqt import QIconifyIcon
app = QApplication([])
btn = QPushButton()
btn.setIcon(QIconifyIcon("fa:smile-o", color="blue"))
btn.setIconSize(QSize(60, 60))
btn.show()
app.exec()
```
A downside of using this is that it's SVG based, which makes it a bit harder …
> feat: add QIcon backed by iconify

- src/superqt/iconify/__init__.py
- tests/test_iconify.py
This PR adds an `addKey` method, similar to `QIcon.addFile`, to QIconifyIcon.  It can be used to add icons/colors for various states/modes:
```python
def addKey(
self,
*key: str,
color: str | None = None,
flip: Flip | None = None,
rotate: Rotation | None = None,
dir: str | None = None,
size: QSize | None = None,
mode: QIcon.Mode = QIcon.Mode.Normal,
state: QIcon.State = QIcon.State.Off,
) -> None:
```
> feat: add addKey method to QIconifyIcon

- src/superqt/spinbox/_intspin.py
- tests/test_large_int_spinbox.py
Closes https://github.com/pyapp-kit/superqt/issues/220
As suggested by Grzegorz here https://github.com/pyapp-kit/superqt/issues/220#issuecomment-1824785806 in this PR I have setMin and setMax check versus the current value and if that is smaller/larger it's reset to min/max.
I also added a test for the issue that fails on current main, but passes with this fix.
> Bugfix: Check min max versus current value

- .github/workflows/test_and_deploy.yml
- src/superqt/sliders/_generic_range_slider.py
- src/superqt/sliders/_generic_slider.py
- src/superqt/sliders/_labeled.py
- src/superqt/sliders/_range_style.py
- src/superqt/utils/_ensure_thread.py
This PR fixes a variety of issues I've encountered, mostly with labeled sliders:
- removes calls to `QApplication.processEvents()` in the labeled sliders.  When using this slider in one of my applications, I was observing some very strange behavior.  Gradually, by removing things piece by piece, I was able to narrow it down to these calls to `processEvents()` in the slider.   The calls are there because, without them, if you interactively do something like `.setEdgeLabelMode(wdg.EdgeLabelMode.NoLabel)`, it will leave the handle labels in a slightly odd position, until the next time the widget is updated (which is likely to be very soon, or at least the next time the slider is touched/moved).  I will try to figure out how to fix that moment of unstyled view, but the consequences of calling …
> fix: fix a number of issues with Labeled and Range Sliders, add LabelsOnHandle mode.

- src/superqt/cmap/_cmap_line_edit.py
small PR that improves the time-to-paint performance of `QColormapLineEdit` (which is used in the cmap combobox).
> perf: improve paint time for QColormapLineEdit

- src/superqt/utils/_code_syntax_highlight.py
Related with https://github.com/napari/napari/issues/6845
Current code computes the full document highlight for each document block/paragraph causing freezes as soon the document content starts to get a little bit long. To reproduce, you can run the `examples/code_highlight.py`, copy and paste the widget text content multiple times (selecting the full content to do a new paste increases the chance to stumble with a freeze in a shorter amount of time). So something like:
This PR tries to prevent/improve the situation by only computing the current block content/text highlight data (not sure if there is a better approach so happy to give a check to any other ideas!). Doing a similar check with the example content copy and paste operations with the changes in this PR:
> Prevent computing full document content highlight per block and only compute current block content for performance

- src/superqt/iconify/__init__.py
QIconifyIcon requires internet connection for the first load (after which it is cached and reused).  However, it still shouldn't fail when offline, so this PR has it fall back to a question mark with a warning, allowing the program to continue loading
> feat: graceful offline fallback for qiconify

- src/superqt/sliders/_labeled.py
makes it easier to override with setylesheets elswhere, like 
```python
app.setStyleSheet("SliderLabel { border: 2px solid black; background-color: lightgray; }")
```
> refactor: remove stylesheet on sliderLabel

- src/superqt/cmap/_cmap_utils.py
Opening this because it resolved my issues in #261.
Unsure about the implications of calling this `QPainter` method, though...
Closes #261
> End painter when drawing colormap

- src/superqt/sliders/_labeled.py
This reverts commit 7e92b8171138438d12d8310d2fc19ce7c943394d.
it had unintended side effects and leads to worse styling overall
> chore: Revert "remove stylesheet on sliderLabel (#254)"

- src/superqt/utils/_code_syntax_highlight.py
I noticed that `CodeSyntaxHighlight` sometimes fails to highlight the texts. This PR fixes the KeyError just by replacing the `__getitem__` with `get`. I encountered this bug when I tried to highlight my pre-commit-config.yaml file, so I cannot tell when this happens.
```python
from superqt.utils import CodeSyntaxHighlight
from qtpy import QtWidgets as QtW
w = QtW.QPlainTextEdit()
highlight = CodeSyntaxHighlight(w.document(), "yaml", "default")
w.setPlainText("ci:\n  autoupdate_schedule: monthly")
```
Output:
```
KeyError                                  Traceback (most recent call last)
File ~\Desktop\code\python\superqt\src\superqt\utils\_code_syntax_highlight.py:73, in CodeSyntaxHighlight.highlightBlock(self, text)
68 def highlightBlock(self, text):
69     # dirty, dirty hack
70     # …
```
> Fix KeyError in CodeSyntaxHighlight

- .github/workflows/test_and_deploy.yml
- src/superqt/utils/_code_syntax_highlight.py
This PR improves a number of things and fixes some slight issues with `CodeSyntaxHighlight`:
- adds full type hinting, including `KnownStyle` for IDE suggestions of valid pygments names
- prevents Formatter from overriding all font selections on the parent object.  I tried to apply fonts and found that `get_text_char_format` was always clobbering whatever I did.  Furthermore, it wasn't successfully applying "Monospace", instead I get: `WARNING: Populating font family aliases took 75 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.`.  So this adds a full font family tree that should work on any system, *and* it only applies it if the style explicitly sets the "mono" flag.  This means that most users will now need to set Monospace themselves (but …
> feat: Improve CodeSyntaxHighlight object

- docs/widgets/index.md
- docs/widgets/qflowlayout.md
- examples/flow_layout.py
- src/superqt/__init__.py
- src/superqt/utils/__init__.py
- src/superqt/utils/_flow_layout.py
- tests/test_flow_layout.py
This adds the QFlowLayout described at https://doc.qt.io/qt-6/qtwidgets-layouts-flowlayout-example.html
https://github.com/user-attachments/assets/b0708de8-2ffa-401b-9032-2480d70f09e0
> feat: add QFlowLayout, for variable width widgets

- src/superqt/__init__.py
- src/superqt/iconify/__init__.py
I found that ~50% of the import time of `superqt` originates from `pyconify` even though only `QIconifyIcon` depends on it.
This PR moves the import statements inside the methods.
In my local environment, the execution time of `import superqt` was:
main: 0.864 s (pyconify: 0.445 s)
this PR: 0.436 s
> Lazy-import `pyconify`

- examples/toggle_switch.py
- src/superqt/__init__.py
- src/superqt/switch/__init__.py
- src/superqt/switch/_toggle_switch.py
- tests/test_toggle_switch.py
I have been using toggle switch in many places of my repositories and I thought that it would be better to have one in superqt.
> feat: toggle switch

- src/superqt/utils/_img_utils.py
Make sure the returned ndarray is ordered the same as on little
endian systems.
Solves #287
> Make qimage_to_array() work on big endian

- src/superqt/sliders/_labeled.py
Follow up to #226. 
Solves problem pointed out by @psobolewskiPhD  https://github.com/napari/napari/pull/8184#issuecomment-3141341450
I found that, even if parent is set, the qss rules are not applied. 
I found that recalculation of size may be triggered on showEvent. 
Other option is to check for `StyleChange` event in `changeEvent` method
> fix: Fix size of Slider label to not ocupy to much space
